import { 
  User, Building, Floor, RoomType, Room, Bed, Institution, Guest, Group, 
  Reservation, RoomAssignment, Facility, RateItem, Invoice, InvoiceItem, 
  Payment, HousekeepingTask, MaintenanceRequest, NotificationItem, AuditLog, AppSettings,
  RoomStatus, HousekeepingStatus 
} from '../types';

export const initialSettings: AppSettings = {
  app_name: 'SIMAHA PAPUA',
  app_title: 'SIMAHA — Sistem Informasi Manajemen Asrama Haji',
  app_subtitle: 'Sistem Informasi Manajemen Asrama Haji Provinsi Papua',
  organization_name: 'Unit Pelaksana Teknis Asrama Haji Provinsi Papua',
  address: 'Jl. Raya Sentani - Padang Bulan, Kotaraja, Distrik Abepura',
  city: 'Kota Jayapura',
  province: 'Papua',
  phone: '(0967) 581234 / +62 812-4821-9988',
  email: 'upt.asramahaji.papua@kemenag.go.id',
  head_officer: 'Kepala UPT Asrama Haji Papua',
  head_nip: '19710815 199803 1 004',
  bank_bpd_papua: 'Bank Papua: 100-02-01-88990-1 a/n BPn Asrama Haji Papua',
  bank_bsi: 'Bank Syariah Indonesia: 7123-4567-89 a/n UPT Asrama Haji Jayapura',
  bank_bri: 'Bank Rakyat Indonesia: 0021-01-000888-30-2 a/n Pengelola Asrama Haji Papua',
  checkin_time_default: '14:00',
  checkout_time_default: '12:00',
  timezone: 'Asia/Jayapura (WIT - UTC+9)',
};

export const initialUsers: User[] = [
  {
    id: 'usr-001',
    username: 'superadmin',
    name: 'Super Admin',
    email: 'superadmin@asramahaji.id',
    role: 'SUPER_ADMIN',
    avatar: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=150',
    department: 'Pranata Komputer & IT',
    status: 'ACTIVE',
    last_login: '2026-09-26T15:30:00Z',
    created_at: '2026-01-10T08:00:00Z',
  },
  {
    id: 'usr-002',
    username: 'admin',
    name: 'Admin Penginapan',
    email: 'admin@asramahaji.id',
    role: 'ADMIN_PENGINAPAN',
    avatar: 'https://images.unsplash.com/photo-1544005313-94ddf0286df2?w=150',
    department: 'Seksi Pelayanan & Akomodasi',
    status: 'ACTIVE',
    last_login: '2026-09-26T14:45:00Z',
    created_at: '2026-01-15T09:00:00Z',
  },
  {
    id: 'usr-003',
    username: 'resepsionis',
    name: 'Resepsionis',
    email: 'resepsionis@asramahaji.id',
    role: 'RESEPSIONIS',
    avatar: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=150',
    department: 'Front Desk & Kasir',
    status: 'ACTIVE',
    last_login: '2026-09-26T15:10:00Z',
    created_at: '2026-02-01T08:30:00Z',
  },
  {
    id: 'usr-004',
    username: 'keuangan',
    name: 'Bendahara Keuangan',
    email: 'keuangan@asramahaji.id',
    role: 'KEUANGAN',
    avatar: 'https://images.unsplash.com/photo-1573496359142-b8d87734a5a2?w=150',
    department: 'Bendahara Penerimaan Pembantu (BPP)',
    status: 'ACTIVE',
    last_login: '2026-09-26T11:20:00Z',
    created_at: '2026-01-20T08:00:00Z',
  },
  {
    id: 'usr-005',
    username: 'housekeeping',
    name: 'Housekeeping',
    email: 'housekeeping@asramahaji.id',
    role: 'HOUSEKEEPING',
    avatar: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=150',
    department: 'Koordinator Kebersihan & Tata Graha',
    status: 'ACTIVE',
    last_login: '2026-09-26T13:00:00Z',
    created_at: '2026-02-10T07:00:00Z',
  },
  {
    id: 'usr-006',
    username: 'pimpinan',
    name: 'Pimpinan (Ka. UPT)',
    email: 'pimpinan@asramahaji.id',
    role: 'PIMPINAN',
    avatar: 'https://images.unsplash.com/photo-1472099645785-5658abf4ff4e?w=150',
    department: 'Kepala UPT Asrama Haji Papua',
    status: 'ACTIVE',
    last_login: '2026-09-26T09:15:00Z',
    created_at: '2026-01-05T08:00:00Z',
  },
];

export const initialBuildings: Building[] = [
  {
    id: 'bld-01',
    code: 'GDA',
    name: 'Gedung Nabire',
    total_floors: 3,
    description: 'Gedung akomodasi utama dengan fasilitas Standard & VIP, dekat dengan Aula Pertemuan',
    status: 'ACTIVE',
    created_at: '2026-01-01T00:00:00Z',
  },
  {
    id: 'bld-02',
    code: 'GDB',
    name: 'Gedung Jayapura',
    total_floors: 3,
    description: 'Gedung akomodasi jamaah dan rombongan berkapasitas besar, akses cepat ke Masjid',
    status: 'ACTIVE',
    created_at: '2026-01-01T00:00:00Z',
  },
  {
    id: 'bld-03',
    code: 'GDC',
    name: 'Gedung Merauke',
    total_floors: 2,
    description: 'Gedung khusus peserta pelatihan teknis, bimtek, dan ruang penginapan VIP pimpinan',
    status: 'ACTIVE',
    created_at: '2026-01-01T00:00:00Z',
  },
];

export const initialFloors: Floor[] = [
  { id: 'flr-01', building_id: 'bld-01', floor_number: 1, name: 'Lantai 1 Gedung Nabire' },
  { id: 'flr-02', building_id: 'bld-01', floor_number: 2, name: 'Lantai 2 Gedung Nabire' },
  { id: 'flr-03', building_id: 'bld-01', floor_number: 3, name: 'Lantai 3 Gedung Nabire' },
  { id: 'flr-04', building_id: 'bld-02', floor_number: 1, name: 'Lantai 1 Gedung Jayapura' },
  { id: 'flr-05', building_id: 'bld-02', floor_number: 2, name: 'Lantai 2 Gedung Jayapura' },
  { id: 'flr-06', building_id: 'bld-02', floor_number: 3, name: 'Lantai 3 Gedung Jayapura' },
  { id: 'flr-07', building_id: 'bld-03', floor_number: 1, name: 'Lantai 1 Gedung Merauke' },
  { id: 'flr-08', building_id: 'bld-03', floor_number: 2, name: 'Lantai 2 Gedung Merauke' },
];

export const initialRoomTypes: RoomType[] = [
  {
    id: 'rt-std',
    code: 'STD',
    name: 'Kamar Standard Quad',
    description: 'Kamar 4 tempat tidur dengan pendingin ruangan AC, kamar mandi dalam, lemari pakaian individual.',
    default_capacity: 4,
    base_rate_per_night: 350000,
    amenities: ['AC', 'Kamar Mandi Dalam', 'Water Heater', 'Lemari Pakaian 4 Pintu', 'Meja Kerja', 'WiFi Gratis', 'Handuk & Sabun'],
  },
  {
    id: 'rt-vip',
    code: 'VIP',
    name: 'Kamar VIP Twin / Double',
    description: 'Kamar eksekutif berkapasitas 2 orang, cocok untuk narasumber, pejabat kementerian, atau tamu dinas.',
    default_capacity: 2,
    base_rate_per_night: 550000,
    amenities: ['AC Dual-Inverter', 'Kamar Mandi Mewah + Water Heater', 'Smart TV 43 Inch', 'Kulkas Mini', 'Coffee & Tea Maker', 'Lemari Jati', 'Sofa Santai', 'WiFi High Speed'],
  },
  {
    id: 'rt-rbg',
    code: 'RBG',
    name: 'Kamar Rombongan / Asrama',
    description: 'Kamar berkapasitas 6 tempat tidur dirancang khusus untuk rombongan jamaah haji / peserta pelatihan massal.',
    default_capacity: 6,
    base_rate_per_night: 500000,
    amenities: ['AC Sentral', '2 Kamar Mandi Dalam', 'Locker Individu Kunci', 'Tempat Wudhu Dalam', 'Stop Kontak Tiap Bed', 'WiFi'],
  },
  {
    id: 'rt-ste',
    code: 'SUITE',
    name: 'Presidential / VIP Suite',
    description: 'Kamar kelas tertinggi dengan ruang tamu terpisah, meja kerja dinas, dan fasilitas kenegaraan.',
    default_capacity: 2,
    base_rate_per_night: 850000,
    amenities: ['Ruang Tamu Terpisah', 'Smart TV 55 Inch', 'Mini Pantry & Microwave', 'Kamar Mandi Bath-tub', 'Meja Rapat Kecil', 'AC Split tiap ruangan'],
  },
];

export const initialInstitutions: Institution[] = [
  {
    id: 'inst-01',
    name: 'Kantor Wilayah Kementerian Agama Provinsi Papua',
    type: 'KEMENAG',
    address: 'Jl. Raya Abepura - Kotaraja, Kota Jayapura',
    phone: '(0967) 581122',
    contact_person: 'H. Rusli Sanjaya, M.Si. (0812-4820-1122)',
    email: 'papua@kemenag.go.id',
  },
  {
    id: 'inst-02',
    name: 'Pemerintah Daerah Kabupaten Jayapura (Bagian Kesra)',
    type: 'PEMDA',
    address: 'Kompleks Perkantoran Gunung Merah Sentani, Jayapura',
    phone: '(0967) 591230',
    contact_person: 'Yakobus Weya, S.STP (0821-9988-7711)',
    email: 'kesra@jayapurakab.go.id',
  },
  {
    id: 'inst-03',
    name: 'Kantor Kementerian Agama Kabupaten Merauke',
    type: 'KEMENAG',
    address: 'Jl. TMP Trikora, Merauke, Papua Selatan',
    phone: '(0971) 321890',
    contact_person: 'Drs. H. Mulyadi (0813-4455-6677)',
    email: 'kemenag.merauke@kemenag.go.id',
  },
  {
    id: 'inst-04',
    name: 'IAIN Fattahul Muluk Papua',
    type: 'DINAS',
    address: 'Jl. Merauke No. 1, Buper Waena, Kota Jayapura',
    phone: '(0967) 572111',
    contact_person: 'Dr. Hj. Siti Fatimah, M.Ag (0852-5400-3321)',
    email: 'humas@iainpapua.ac.id',
  },
  {
    id: 'inst-05',
    name: 'Balai Penjaminan Mutu Pendidikan (BPMP) Papua',
    type: 'DINAS',
    address: 'Jl. Kotaraja Dalam, Kota Jayapura',
    phone: '(0967) 581555',
    contact_person: 'Maria Kogoya, S.Pd (0812-4099-2311)',
    email: 'bpmp.papua@kemdikbud.go.id',
  },
  {
    id: 'inst-06',
    name: 'Kelompok Bimbingan Ibadah Haji & Umrah (KBIHU) Babussalam Jayapura',
    type: 'KOMUNITAS',
    address: 'Jl. Percetakan Negara No. 45, Jayapura Utara',
    phone: '(0967) 534889',
    contact_person: 'K.H. Ahmad Dahlan (0811-480-998)',
    email: 'kbihu.babussalam@gmail.com',
  },
];

// Helper to generate 24 rooms across 3 buildings
export function generateSeedRoomsAndBeds(): { rooms: Room[]; beds: Bed[] } {
  const rooms: Room[] = [];
  const beds: Bed[] = [];

  const roomConfig = [
    // Gedung A (Nabire) - Lantai 1 (Standard 4 Bed)
    { num: 'A101', bld: 'bld-01', flr: 'flr-01', type: 'rt-std', cap: 4, rate: 350000, status: 'OCCUPIED' as RoomStatus, hk: 'INSPECTED' as HousekeepingStatus },
    { num: 'A102', bld: 'bld-01', flr: 'flr-01', type: 'rt-std', cap: 4, rate: 350000, status: 'OCCUPIED' as RoomStatus, hk: 'READY' as HousekeepingStatus },
    { num: 'A103', bld: 'bld-01', flr: 'flr-01', type: 'rt-std', cap: 4, rate: 350000, status: 'RESERVED' as RoomStatus, hk: 'READY' as HousekeepingStatus },
    { num: 'A104', bld: 'bld-01', flr: 'flr-01', type: 'rt-std', cap: 4, rate: 350000, status: 'CLEANING' as RoomStatus, hk: 'DIRTY' as HousekeepingStatus },
    { num: 'A105', bld: 'bld-01', flr: 'flr-01', type: 'rt-std', cap: 4, rate: 350000, status: 'MAINTENANCE' as RoomStatus, hk: 'IN_CLEANING' as HousekeepingStatus },
    { num: 'A106', bld: 'bld-01', flr: 'flr-01', type: 'rt-std', cap: 4, rate: 350000, status: 'AVAILABLE' as RoomStatus, hk: 'READY' as HousekeepingStatus },
    { num: 'A107', bld: 'bld-01', flr: 'flr-01', type: 'rt-std', cap: 4, rate: 350000, status: 'AVAILABLE' as RoomStatus, hk: 'READY' as HousekeepingStatus },
    { num: 'A108', bld: 'bld-01', flr: 'flr-01', type: 'rt-std', cap: 4, rate: 350000, status: 'AVAILABLE' as RoomStatus, hk: 'READY' as HousekeepingStatus },
    
    // Gedung A (Nabire) - Lantai 2 (VIP 2 Bed & Suite)
    { num: 'A201', bld: 'bld-01', flr: 'flr-02', type: 'rt-vip', cap: 2, rate: 550000, status: 'OCCUPIED' as RoomStatus, hk: 'READY' as HousekeepingStatus },
    { num: 'A202', bld: 'bld-01', flr: 'flr-02', type: 'rt-vip', cap: 2, rate: 550000, status: 'OCCUPIED' as RoomStatus, hk: 'READY' as HousekeepingStatus },
    { num: 'A203', bld: 'bld-01', flr: 'flr-02', type: 'rt-vip', cap: 2, rate: 550000, status: 'RESERVED' as RoomStatus, hk: 'READY' as HousekeepingStatus },
    { num: 'A204', bld: 'bld-01', flr: 'flr-02', type: 'rt-vip', cap: 2, rate: 550000, status: 'AVAILABLE' as RoomStatus, hk: 'READY' as HousekeepingStatus },
    { num: 'A205', bld: 'bld-01', flr: 'flr-02', type: 'rt-ste', cap: 2, rate: 850000, status: 'OCCUPIED' as RoomStatus, hk: 'READY' as HousekeepingStatus },
    { num: 'A206', bld: 'bld-01', flr: 'flr-02', type: 'rt-ste', cap: 2, rate: 850000, status: 'AVAILABLE' as RoomStatus, hk: 'READY' as HousekeepingStatus },

    // Gedung B (Jayapura) - Lantai 1 (Rombongan 6 Bed)
    { num: 'B101', bld: 'bld-02', flr: 'flr-04', type: 'rt-rbg', cap: 6, rate: 500000, status: 'OCCUPIED' as RoomStatus, hk: 'READY' as HousekeepingStatus },
    { num: 'B102', bld: 'bld-02', flr: 'flr-04', type: 'rt-rbg', cap: 6, rate: 500000, status: 'OCCUPIED' as RoomStatus, hk: 'READY' as HousekeepingStatus },
    { num: 'B103', bld: 'bld-02', flr: 'flr-04', type: 'rt-rbg', cap: 6, rate: 500000, status: 'RESERVED' as RoomStatus, hk: 'READY' as HousekeepingStatus },
    { num: 'B104', bld: 'bld-02', flr: 'flr-04', type: 'rt-rbg', cap: 6, rate: 500000, status: 'CLEANING' as RoomStatus, hk: 'DIRTY' as HousekeepingStatus },
    { num: 'B105', bld: 'bld-02', flr: 'flr-04', type: 'rt-rbg', cap: 6, rate: 500000, status: 'AVAILABLE' as RoomStatus, hk: 'READY' as HousekeepingStatus },
    { num: 'B106', bld: 'bld-02', flr: 'flr-04', type: 'rt-rbg', cap: 6, rate: 500000, status: 'AVAILABLE' as RoomStatus, hk: 'READY' as HousekeepingStatus },

    // Gedung C (Merauke) - Lantai 1 (Standard 4 Bed)
    { num: 'C101', bld: 'bld-03', flr: 'flr-07', type: 'rt-std', cap: 4, rate: 350000, status: 'OCCUPIED' as RoomStatus, hk: 'READY' as HousekeepingStatus },
    { num: 'C102', bld: 'bld-03', flr: 'flr-07', type: 'rt-std', cap: 4, rate: 350000, status: 'AVAILABLE' as RoomStatus, hk: 'READY' as HousekeepingStatus },
    { num: 'C103', bld: 'bld-03', flr: 'flr-07', type: 'rt-std', cap: 4, rate: 350000, status: 'AVAILABLE' as RoomStatus, hk: 'READY' as HousekeepingStatus },
    { num: 'C104', bld: 'bld-03', flr: 'flr-07', type: 'rt-vip', cap: 2, rate: 550000, status: 'AVAILABLE' as RoomStatus, hk: 'READY' as HousekeepingStatus },
  ];

  roomConfig.forEach((cfg, idx) => {
    const roomId = `room-${(idx + 1).toString().padStart(3, '0')}`;
    let occupiedCount = 0;

    // Generate individual beds
    for (let b = 1; b <= cfg.cap; b++) {
      const bedCode = `${cfg.num}-B0${b}`;
      const bedId = `bed-${roomId}-${b}`;
      let bStatus: 'AVAILABLE' | 'OCCUPIED' | 'RESERVED' | 'MAINTENANCE' = 'AVAILABLE';

      if (cfg.status === 'OCCUPIED') {
        // e.g. for A101, 3 out of 4 occupied
        if (cfg.num === 'A101') {
          bStatus = b <= 3 ? 'OCCUPIED' : 'AVAILABLE';
        } else {
          bStatus = 'OCCUPIED';
        }
      } else if (cfg.status === 'RESERVED') {
        bStatus = 'RESERVED';
      } else if (cfg.status === 'MAINTENANCE') {
        bStatus = 'MAINTENANCE';
      }

      if (bStatus === 'OCCUPIED') {
        occupiedCount++;
      }

      beds.push({
        id: bedId,
        bed_code: bedCode,
        room_id: roomId,
        status: bStatus,
      });
    }

    rooms.push({
      id: roomId,
      room_number: cfg.num,
      building_id: cfg.bld,
      floor_id: cfg.flr,
      room_type_id: cfg.type,
      capacity: cfg.cap,
      total_beds: cfg.cap,
      occupied_beds: occupiedCount,
      rate_per_night: cfg.rate,
      status: cfg.status,
      housekeeping_status: cfg.hk,
      amenities: ['AC', 'WiFi', 'Kamar Mandi Dalam', 'Lemari', 'Meja'],
      notes: cfg.status === 'MAINTENANCE' ? 'Perbaikan unit AC bocor & stop kontak' : undefined,
      created_at: '2026-01-01T00:00:00Z',
      updated_at: '2026-09-26T00:00:00Z',
    });
  });

  return { rooms, beds };
}

export const initialFacilities: Facility[] = [
  {
    id: 'fac-01',
    name: 'Aula Utama Cenderawasih',
    type: 'AULA',
    location: 'Gedung Serbaguna Lantai 1',
    capacity: 500,
    daily_rate: 5000000,
    hourly_rate: 650000,
    status: 'AVAILABLE',
    description: 'Aula besar berpendingin udara dengan panggung kehormatan, sound system 5000 Watt, LED videotron, dan kursi banquet.',
    amenities: ['AC Sentral 10 PK', 'Sound System 5000W + 8 Mic Wireless', 'LED Videotron P3', 'Podium Pidato', '500 Kursi Futura + Cover', 'Ruang Transit VIP'],
  },
  {
    id: 'fac-02',
    name: 'Ruang Pertemuan Asmat',
    type: 'RUANG_RAPAT',
    location: 'Gedung Nabire Lantai 1',
    capacity: 120,
    daily_rate: 2500000,
    hourly_rate: 350000,
    status: 'AVAILABLE',
    description: 'Ruang pertemuan representatif untuk pelatihan dinas, seminar, dan rapat koordinasi instansi.',
    amenities: ['AC 4 Unit', 'Proyektor Epson 4000 Lumens', 'Sound System', 'Meja Seminar', '120 Kursi Banquet', 'Dispenser Air Minum'],
  },
  {
    id: 'fac-03',
    name: 'Ruang Rapat VIP Sentani',
    type: 'RUANG_RAPAT',
    location: 'Gedung Utama Lantai 2',
    capacity: 40,
    daily_rate: 1500000,
    hourly_rate: 250000,
    status: 'AVAILABLE',
    description: 'Ruang rapat VIP dengan meja oval formal, kursi putar kulit, sistem telekonferensi Zoom/Meet.',
    amenities: ['Smart TV 75 Inch Interactive', 'Webcam Conference HD', 'Mikrofon Meja Diskusi', 'AC Split', 'Meja Oval Formal'],
  },
  {
    id: 'fac-04',
    name: 'Masjid Baiturrahim Asrama Haji',
    type: 'MASJID',
    location: 'Kompleks Depan Asrama Haji',
    capacity: 600,
    daily_rate: 0,
    status: 'AVAILABLE',
    description: 'Masjid utama jemaah haji Papua dengan karpet tebal, sound system adzan merdu, tempat wudhu luas dan toilet syar’i.',
    amenities: ['Karpet Tebal Turki', 'Sound System Masjid', 'Tempat Wudhu Terpisah Pria/Wanita', 'Kipas Angin Besar', 'Mimbar Khutbah Jati'],
  },
  {
    id: 'fac-05',
    name: 'Lapangan Terbuka Manasik Haji',
    type: 'LAPANGAN_MANASIK',
    location: 'Area Terbuka Kompleks Timur',
    capacity: 1000,
    daily_rate: 2000000,
    status: 'AVAILABLE',
    description: 'Area praktek manasik haji outdoor dengan replika Ka’bah berskala 1:1, replika bukit Shafa-Marwah, area lontar Jumrah, dan tenda Mina.',
    amenities: ['Replika Ka’bah 1:1', 'Lintasan Sa’i Shafa-Marwah', 'Replika Tugu Jamarat', 'Speaker Outdoor', 'Tenda Transit Peneduh'],
  },
  {
    id: 'fac-06',
    name: 'Ruang Makan Serbaguna',
    type: 'RUANG_MAKAN',
    location: 'Sebelah Gedung Jayapura',
    capacity: 300,
    daily_rate: 1800000,
    status: 'AVAILABLE',
    description: 'Ruang makan prasmanan higienis dengan meja panjang, tempat cuci tangan berlimpah, dan sirkulasi udara optimal.',
    amenities: ['Meja Prasmanan Stainless Steel', 'Pemanas Makanan (Chafing Dish)', 'Wastafel Otomatis', 'Air Bersih Terfiltrasi'],
  },
];

export const initialGuests: Guest[] = [
  {
    id: 'gst-001',
    nik: '9171011504780002',
    full_name: 'Drs. H. Syamsuddin, M.Ag.',
    gender: 'L',
    phone: '0812-4820-9911',
    email: 'syamsuddin.kemenag@gmail.com',
    institution_id: 'inst-01',
    guest_type: 'KEDINASAN',
    regency_city: 'Kota Jayapura',
    province: 'Papua',
    address: 'Jl. Sam Ratulangi No. 12, Dok V Atas, Kota Jayapura',
    notes: 'Kepala Bidang PHU Kanwil Kemenag Papua',
    stay_count: 5,
    created_at: '2026-02-10T10:00:00Z',
  },
  {
    id: 'gst-002',
    nik: '9171025508820004',
    full_name: 'Dra. Hj. Maryam Kogoya',
    gender: 'P',
    phone: '0813-4411-2233',
    email: 'maryam.kogoya@jayapurakab.go.id',
    institution_id: 'inst-02',
    guest_type: 'KEDINASAN',
    regency_city: 'Kabupaten Jayapura',
    province: 'Papua',
    address: 'Kompleks Pemda Sentani Blok B No. 4',
    notes: 'Kasi Bimas Islam Kemenag Jayapura',
    stay_count: 3,
    created_at: '2026-03-01T11:00:00Z',
  },
  {
    id: 'gst-003',
    nik: '9171012309850001',
    full_name: 'H. Abdul Ghofur, S.Pd.I',
    gender: 'L',
    phone: '0852-4412-8877',
    email: 'abdul.ghofur85@gmail.com',
    institution_id: 'inst-06',
    guest_type: 'MANASIK',
    regency_city: 'Kabupaten Keerom',
    province: 'Papua',
    address: 'Jl. Trans Papua Arso II, Keerom',
    notes: 'Pembimbing Ibadah Kloter Jayapura',
    stay_count: 8,
    created_at: '2026-01-15T09:30:00Z',
  },
  {
    id: 'gst-004',
    nik: '9171036012890003',
    full_name: 'Fatimah Az-Zahra, S.H.',
    gender: 'P',
    phone: '0821-9876-5432',
    email: 'fatimah.azzahra@iainpapua.ac.id',
    institution_id: 'inst-04',
    guest_type: 'PELATIHAN',
    regency_city: 'Kota Jayapura',
    province: 'Papua',
    address: 'Buper Waena Blok C, Heram, Kota Jayapura',
    notes: 'Dosen Syariah IAIN Fattahul Muluk',
    stay_count: 2,
    created_at: '2026-04-12T14:00:00Z',
  },
  {
    id: 'gst-005',
    nik: '9301011206740005',
    full_name: 'H. Burhanudin Tabrani',
    gender: 'L',
    phone: '0812-4011-3344',
    email: 'burhan.merauke@yahoo.com',
    institution_id: 'inst-03',
    guest_type: 'JAMAAH',
    regency_city: 'Kabupaten Merauke',
    province: 'Papua Selatan',
    address: 'Jl. Ahmad Yani No. 88, Merauke',
    notes: 'Calon Jamaah Haji Reguler Kloter 1',
    stay_count: 1,
    created_at: '2026-05-18T08:00:00Z',
  },
  {
    id: 'gst-006',
    nik: '9301026507790001',
    full_name: 'Hj. Aminah Wonda',
    gender: 'P',
    phone: '0813-5599-8800',
    email: 'aminah.wonda79@gmail.com',
    institution_id: 'inst-03',
    guest_type: 'JAMAAH',
    regency_city: 'Kabupaten Merauke',
    province: 'Papua Selatan',
    address: 'Jl. Raya Mandala Mopah Lama, Merauke',
    notes: 'Calon Jamaah Haji Reguler Kloter 1',
    stay_count: 1,
    created_at: '2026-05-18T08:10:00Z',
  },
  {
    id: 'gst-007',
    nik: '9103011409860002',
    full_name: 'Muhammad Irfan, M.Pd.',
    gender: 'L',
    phone: '0853-4012-3456',
    email: 'irfan.mimika@kemenag.go.id',
    guest_type: 'PELATIHAN',
    regency_city: 'Kabupaten Mimika',
    province: 'Papua Tengah',
    address: 'Jl. Cenderawasih SP2, Timika',
    notes: 'Peserta Bimtek Guru Madrasah',
    stay_count: 2,
    created_at: '2026-06-20T10:00:00Z',
  },
  {
    id: 'gst-008',
    nik: '9106012211830006',
    full_name: 'Karel Wenda, S.Sos.',
    gender: 'L',
    phone: '0811-482-331',
    email: 'karel.wenda@papua.go.id',
    institution_id: 'inst-02',
    guest_type: 'PEGAWAI',
    regency_city: 'Kabupaten Jayapura',
    province: 'Papua',
    address: 'Doyo Baru, Sentani Barat',
    notes: 'Staff Inspektorat Pendamping Acara',
    stay_count: 4,
    created_at: '2026-07-01T09:00:00Z',
  },
  {
    id: 'gst-009',
    nik: '9105011903900004',
    full_name: 'Ustadz Ridwan Al-Bantani',
    gender: 'L',
    phone: '0822-3819-2244',
    email: 'ridwan.albantani@gmail.com',
    guest_type: 'MANASIK',
    regency_city: 'Kabupaten Biak Numfor',
    province: 'Papua',
    address: 'Jl. Sisingamangaraja No. 3, Biak Kota',
    notes: 'Narasumber Fiqih Haji',
    stay_count: 3,
    created_at: '2026-07-15T13:00:00Z',
  },
  {
    id: 'gst-010',
    nik: '9171015010910007',
    full_name: 'dr. Sarah Maulida, Sp.Ok',
    gender: 'P',
    phone: '0812-9988-1122',
    email: 'dr.sarah.maulida@dinkes.papua.go.id',
    guest_type: 'KEDINASAN',
    regency_city: 'Kota Jayapura',
    province: 'Papua',
    address: 'Jl. Angkasa Raya No. 25, Jayapura Utara',
    notes: 'Tim Kesehatan Haji Indonesia (TKHI) Papua',
    stay_count: 6,
    created_at: '2026-08-01T15:00:00Z',
  },
  {
    id: 'gst-011',
    nik: '9171010101800008',
    full_name: 'H. Muchtar Sembiring, S.E.',
    gender: 'L',
    phone: '0813-4400-9988',
    email: 'muchtar.sembiring@gmail.com',
    guest_type: 'UMUM',
    regency_city: 'Kota Jayapura',
    province: 'Papua',
    address: 'Jl. Kelapa Dua Entrop, Distrik Jayapura Selatan',
    notes: 'Tamu keluarga jamaah',
    stay_count: 1,
    created_at: '2026-08-10T11:00:00Z',
  },
  {
    id: 'gst-012',
    nik: '9171026006880009',
    full_name: 'Hj. Kartini Maturbongs',
    gender: 'P',
    phone: '0852-4499-1122',
    guest_type: 'JAMAAH',
    regency_city: 'Kabupaten Merauke',
    province: 'Papua Selatan',
    address: 'Jl. Postel Mopah Lama, Merauke',
    notes: 'Peserta Rombongan Jamaah Haji Kloter 1',
    stay_count: 1,
    created_at: '2026-09-01T09:00:00Z',
  },
];

export const initialGroups: Group[] = [
  {
    id: 'grp-01',
    group_name: 'Rombongan Calon Jamaah Haji Kloter 1 Jayapura & Merauke',
    activity_name: 'Pemberangkatan & Pemantapan Ibadah Calon Jamaah Haji 1447H / 2026M',
    institution_id: 'inst-01',
    pic_name: 'H. Abdul Ghofur, S.Pd.I',
    pic_phone: '0852-4412-8877',
    pic_email: 'abdul.ghofur85@gmail.com',
    total_members: 45,
    male_count: 24,
    female_count: 21,
    checkin_date: '2026-09-25',
    checkout_date: '2026-09-28',
    notes: 'Rombongan menginap 3 malam sebelum terbang menuju Embarkasi Makassar (UPG). Memerlukan bimbingan manasik intensif.',
    created_at: '2026-09-10T08:00:00Z',
  },
  {
    id: 'grp-02',
    group_name: 'Peserta Bimbingan Teknis Sertifikasi Pembimbing Manasik Papua',
    activity_name: 'Bimtek Sertifikasi Pembimbing Manasik Haji Profesional Kemenag Papua',
    institution_id: 'inst-01',
    pic_name: 'Dr. Hj. Siti Fatimah, M.Ag',
    pic_phone: '0852-5400-3321',
    pic_email: 'humas@iainpapua.ac.id',
    total_members: 30,
    male_count: 18,
    female_count: 12,
    checkin_date: '2026-09-26',
    checkout_date: '2026-09-29',
    notes: 'Membutuhkan Aula Cenderawasih & konsumsi 3x sehari + 2x snack',
    created_at: '2026-09-12T09:30:00Z',
  },
  {
    id: 'grp-03',
    group_name: 'Peserta Pelatihan Guru Madrasah Ibtidaiyah se-Papua',
    activity_name: 'Peningkatan Kompetensi Pedagogik Guru Madrasah Ibtidaiyah',
    institution_id: 'inst-05',
    pic_name: 'Maria Kogoya, S.Pd',
    pic_phone: '0812-4099-2311',
    total_members: 20,
    male_count: 10,
    female_count: 10,
    checkin_date: '2026-09-28',
    checkout_date: '2026-10-01',
    notes: 'Menunggu konfirmasi verifikasi dari Kepala Asrama Haji',
    created_at: '2026-09-24T14:20:00Z',
  },
];

export const initialReservations: Reservation[] = [
  {
    id: 'rsv-001',
    reservation_no: 'RSV/AHP/2026/00001',
    reservation_date: '2026-09-20T08:00:00Z',
    reservation_type: 'ROMBONGAN',
    guest_id: 'gst-003',
    group_id: 'grp-01',
    institution_id: 'inst-01',
    activity_type: 'HAJI_UMRAH',
    activity_name: 'Pemberangkatan Calon Jamaah Haji Kloter 1',
    checkin_date: '2026-09-25',
    checkout_date: '2026-09-28',
    total_guests: 45,
    male_count: 24,
    female_count: 21,
    total_rooms_requested: 10,
    facility_requirements: 'Aula Cenderawasih, Lapangan Manasik, Konsumsi Prasmanan 3x Sehari',
    status: 'CHECKED_IN',
    payment_status: 'PAID',
    total_amount: 28500000,
    paid_amount: 28500000,
    remaining_amount: 0,
    notes: 'Rombongan utama Kloter 1, check-in tanggal 25 Sept pukul 14:00 WIT.',
    spma_no: 'SPMA/AHP/2026/09/0001',
    package_type: 'MANASIK_AKBAR',
    created_by: 'Admin Penginapan',
    verified_by: 'Pimpinan (Ka. UPT)',
    verified_at: '2026-09-21T10:00:00Z',
    created_at: '2026-09-20T08:00:00Z',
    updated_at: '2026-09-25T14:30:00Z',
  },
  {
    id: 'rsv-002',
    reservation_no: 'RSV/AHP/2026/00002',
    reservation_date: '2026-09-21T09:15:00Z',
    reservation_type: 'ROMBONGAN',
    guest_id: 'gst-004',
    group_id: 'grp-02',
    institution_id: 'inst-01',
    activity_type: 'BIMTEK',
    activity_name: 'Bimtek Sertifikasi Pembimbing Manasik Papua',
    checkin_date: '2026-09-26',
    checkout_date: '2026-09-29',
    total_guests: 30,
    male_count: 18,
    female_count: 12,
    total_rooms_requested: 7,
    facility_requirements: 'Ruang Pertemuan Asmat & Sound System',
    status: 'CHECKED_IN',
    payment_status: 'PARTIAL',
    total_amount: 19800000,
    paid_amount: 10000000,
    remaining_amount: 9800000,
    notes: 'Check-in hari ini Sabtu 26 September pukul 11:30 WIT.',
    spma_no: 'SPMA/AHP/2026/09/0002',
    package_type: 'FULLBOARD_DIKLAT',
    created_by: 'Resepsionis',
    verified_by: 'Admin Penginapan',
    verified_at: '2026-09-22T08:45:00Z',
    created_at: '2026-09-21T09:15:00Z',
    updated_at: '2026-09-26T11:30:00Z',
  },
  {
    id: 'rsv-003',
    reservation_no: 'RSV/AHP/2026/00003',
    reservation_date: '2026-09-22T11:00:00Z',
    reservation_type: 'INDIVIDUAL',
    guest_id: 'gst-001',
    institution_id: 'inst-01',
    activity_type: 'KEDINASAN',
    activity_name: 'Kunjungan Kerja Evaluasi Penginapan Haji',
    checkin_date: '2026-09-25',
    checkout_date: '2026-09-27',
    total_guests: 1,
    male_count: 1,
    female_count: 0,
    total_rooms_requested: 1,
    status: 'CHECKED_IN',
    payment_status: 'PAID',
    total_amount: 1100000,
    paid_amount: 1100000,
    remaining_amount: 0,
    notes: 'Kamar VIP A201 (Twin). Menginap 2 malam.',
    spma_no: 'SPMA/AHP/2026/09/0003',
    package_type: 'REGULER',
    created_by: 'Resepsionis',
    verified_by: 'Admin Penginapan',
    verified_at: '2026-09-22T13:00:00Z',
    created_at: '2026-09-22T11:00:00Z',
    updated_at: '2026-09-25T15:00:00Z',
  },
  {
    id: 'rsv-004',
    reservation_no: 'RSV/AHP/2026/00004',
    reservation_date: '2026-09-23T14:30:00Z',
    reservation_type: 'INDIVIDUAL',
    guest_id: 'gst-010',
    institution_id: 'inst-01',
    activity_type: 'KEDINASAN',
    activity_name: 'Pemeriksaan Kesehatan Awal Jamaah',
    checkin_date: '2026-09-25',
    checkout_date: '2026-09-28',
    total_guests: 1,
    male_count: 0,
    female_count: 1,
    total_rooms_requested: 1,
    status: 'CHECKED_IN',
    payment_status: 'PAID',
    total_amount: 1650000,
    paid_amount: 1650000,
    remaining_amount: 0,
    notes: 'Kamar VIP A202. Tim Kesehatan Haji Indonesia.',
    created_by: 'Resepsionis',
    verified_by: 'Admin Penginapan',
    verified_at: '2026-09-23T15:00:00Z',
    created_at: '2026-09-23T14:30:00Z',
    updated_at: '2026-09-25T14:15:00Z',
  },
  {
    id: 'rsv-005',
    reservation_no: 'RSV/AHP/2026/00005',
    reservation_date: '2026-09-24T16:00:00Z',
    reservation_type: 'ROMBONGAN',
    guest_id: 'gst-007',
    group_id: 'grp-03',
    institution_id: 'inst-05',
    activity_type: 'PELATIHAN',
    activity_name: 'Peningkatan Kompetensi Guru MI Papua',
    checkin_date: '2026-09-28',
    checkout_date: '2026-10-01',
    total_guests: 20,
    male_count: 10,
    female_count: 10,
    total_rooms_requested: 5,
    facility_requirements: 'Ruang Kelas Pelatihan & Ruang Makan',
    status: 'PENDING', // Waiting verification!
    payment_status: 'UNPAID',
    total_amount: 12500000,
    paid_amount: 0,
    remaining_amount: 12500000,
    notes: 'Permohonan baru masuk kemarin sore, menunggu verifikasi pengelola.',
    created_by: 'Resepsionis',
    created_at: '2026-09-24T16:00:00Z',
    updated_at: '2026-09-24T16:00:00Z',
  },
  {
    id: 'rsv-006',
    reservation_no: 'RSV/AHP/2026/00006',
    reservation_date: '2026-09-25T10:00:00Z',
    reservation_type: 'INDIVIDUAL',
    guest_id: 'gst-009',
    activity_type: 'MANASIK',
    activity_name: 'Narasumber Kajian Fiqih Manasik Akbar',
    checkin_date: '2026-09-26', // Hari ini!
    checkout_date: '2026-09-28',
    total_guests: 1,
    male_count: 1,
    female_count: 0,
    total_rooms_requested: 1,
    status: 'CONFIRMED', // Check-in today!
    payment_status: 'PAID',
    total_amount: 1100000,
    paid_amount: 1100000,
    remaining_amount: 0,
    notes: 'Kamar VIP A203 sudah dipersiapkan dan ready.',
    created_by: 'Admin Penginapan',
    verified_by: 'Pimpinan (Ka. UPT)',
    verified_at: '2026-09-25T11:00:00Z',
    created_at: '2026-09-25T10:00:00Z',
    updated_at: '2026-09-25T11:00:00Z',
  },
  {
    id: 'rsv-007',
    reservation_no: 'RSV/AHP/2026/00007',
    reservation_date: '2026-09-22T08:00:00Z',
    reservation_type: 'INDIVIDUAL',
    guest_id: 'gst-011',
    activity_type: 'UMUM',
    activity_name: 'Menginap Pribadi Keluarga Jamaah',
    checkin_date: '2026-09-23',
    checkout_date: '2026-09-26', // Checkout Hari ini!
    total_guests: 2,
    male_count: 1,
    female_count: 1,
    total_rooms_requested: 1,
    status: 'CHECKED_OUT', // Checked out today
    payment_status: 'PAID',
    total_amount: 1050000,
    paid_amount: 1050000,
    remaining_amount: 0,
    notes: 'Kamar A104 telah checkout pukul 11:45 WIT, status kamar Dirty/Cleaning.',
    created_by: 'Resepsionis',
    verified_by: 'Admin Penginapan',
    verified_at: '2026-09-22T09:00:00Z',
    created_at: '2026-09-22T08:00:00Z',
    updated_at: '2026-09-26T11:45:00Z',
  },
];

export const initialHousekeepingTasks: HousekeepingTask[] = [
  {
    id: 'hk-01',
    room_id: 'room-004', // A104 (checkout today)
    task_type: 'POST_CHECKOUT',
    status: 'DIRTY',
    priority: 'HIGH',
    assigned_to: 'Housekeeping',
    started_at: '2026-09-26T12:00:00Z',
    notes: 'Ganti seprei, sarung bantal, sanitasi kamar mandi dan buang sampah setelah tamu checkout.',
    room_condition: 'Kondisi kamar baik, fasilitas lengkap tidak ada barang tertinggal.',
    created_at: '2026-09-26T11:45:00Z',
  },
  {
    id: 'hk-02',
    room_id: 'room-016', // B104
    task_type: 'REGULAR_CLEAN',
    status: 'IN_CLEANING',
    priority: 'MEDIUM',
    assigned_to: 'Yance Matuan',
    started_at: '2026-09-26T14:00:00Z',
    notes: 'Pembersihan berkala dan pengecekan linen kamar asrama.',
    created_at: '2026-09-26T13:30:00Z',
  },
  {
    id: 'hk-03',
    room_id: 'room-001', // A101
    task_type: 'INSPECTION',
    status: 'INSPECTED',
    priority: 'LOW',
    assigned_to: 'Housekeeping',
    started_at: '2026-09-26T09:00:00Z',
    completed_at: '2026-09-26T09:45:00Z',
    inspected_by: 'Admin Penginapan',
    notes: 'Kamar telah diinspeksi dan dinyatakan sangat bersih dan rapi.',
    room_condition: 'Sangat baik',
    created_at: '2026-09-26T08:30:00Z',
  },
];

export const initialMaintenanceRequests: MaintenanceRequest[] = [
  {
    id: 'mnt-01',
    ticket_no: 'MNT/AHP/2026/0001',
    room_id: 'room-005', // A105
    issue_category: 'AC_HVAC',
    priority: 'URGENT',
    description: 'Unit AC kamar A105 meneteskan air deras dan udara tidak dingin. Perlu pembersihan filter & perbaikan pipa pembuangan (drain pipe).',
    reporter_name: 'Resepsionis',
    assigned_technician: 'Lukas Karoba (Teknisi HVAC)',
    status: 'IN_PROGRESS',
    reported_at: '2026-09-26T08:30:00Z',
    estimated_cost: 350000,
    notes: 'Kamar A105 dinonaktifkan sementara (Status: MAINTENANCE) hingga pengerjaan selesai.',
  },
  {
    id: 'mnt-02',
    ticket_no: 'MNT/AHP/2026/0002',
    room_id: 'room-002', // A102
    issue_category: 'PLUMBING',
    priority: 'LOW',
    description: 'Kran wastafel sedikit menetes, perlu pergantian seal karet.',
    reporter_name: 'Housekeeping',
    assigned_technician: 'Lukas Karoba',
    status: 'OPEN',
    reported_at: '2026-09-26T10:15:00Z',
    estimated_cost: 75000,
  },
];

export const initialInvoices: Invoice[] = [
  {
    id: 'inv-001',
    invoice_no: 'INV/AHP/2026/0001',
    reservation_id: 'rsv-001',
    bill_to_name: 'H. Abdul Ghofur, S.Pd.I / Kemenag Papua',
    institution_name: 'Kantor Wilayah Kementerian Agama Provinsi Papua',
    issue_date: '2026-09-21',
    due_date: '2026-09-25',
    subtotal: 28500000,
    discount_amount: 0,
    tax_amount: 0,
    extra_charges: 0,
    total_amount: 28500000,
    paid_amount: 28500000,
    balance_due: 0,
    status: 'PAID',
    pnbp_account_code: '425112',
    pnbp_account_name: 'Pendapatan Sewa Kamar / Asrama / Wisma (PP No. 59/2020)',
    simponi_billing_code: '82026092600101',
    billing_expired_at: '2026-09-28T23:59:59Z',
    spk_contract_no: 'SPK/AHP/KS/2026/001',
    notes: 'Biaya paket penginapan dan penggunaan fasilitas Jamaah Haji Kloter 1 Jayapura',
    created_at: '2026-09-21T10:00:00Z',
  },
  {
    id: 'inv-002',
    invoice_no: 'INV/AHP/2026/0002',
    reservation_id: 'rsv-002',
    bill_to_name: 'Dr. Hj. Siti Fatimah, M.Ag',
    institution_name: 'IAIN Fattahul Muluk Papua',
    issue_date: '2026-09-22',
    due_date: '2026-09-27',
    subtotal: 19800000,
    discount_amount: 0,
    tax_amount: 0,
    extra_charges: 0,
    total_amount: 19800000,
    paid_amount: 10000000,
    balance_due: 9800000,
    status: 'PARTIAL',
    pnbp_account_code: '425111',
    pnbp_account_name: 'Pendapatan Sewa Gedung, Bangunan, Ruangan & Fasilitas Aula',
    simponi_billing_code: '82026092600202',
    billing_expired_at: '2026-09-29T23:59:59Z',
    spk_contract_no: 'SPK/AHP/KS/2026/002',
    notes: 'Telah dibayar DP sebesar Rp 10.000.000 via Transfer BSI. Sisa pelunasan sebelum checkout.',
    created_at: '2026-09-22T11:00:00Z',
  },
  {
    id: 'inv-003',
    invoice_no: 'INV/AHP/2026/0003',
    reservation_id: 'rsv-003',
    bill_to_name: 'Drs. H. Syamsuddin, M.Ag.',
    institution_name: 'Kantor Wilayah Kementerian Agama Provinsi Papua',
    issue_date: '2026-09-22',
    due_date: '2026-09-25',
    subtotal: 1100000,
    discount_amount: 0,
    tax_amount: 0,
    extra_charges: 0,
    total_amount: 1100000,
    paid_amount: 1100000,
    balance_due: 0,
    status: 'PAID',
    pnbp_account_code: '425112',
    pnbp_account_name: 'Pendapatan Sewa Kamar / Asrama / Wisma (PP No. 59/2020)',
    simponi_billing_code: '82026092600303',
    billing_expired_at: '2026-09-27T23:59:59Z',
    notes: 'Menginap 2 malam Kamar VIP A201',
    created_at: '2026-09-22T13:30:00Z',
  },
];

export const initialInvoiceItems: InvoiceItem[] = [
  {
    id: 'ii-01',
    invoice_id: 'inv-001',
    description: 'Sewa Kamar Rombongan Jamaah Haji (8 Kamar x 3 Malam)',
    category: 'ROOM',
    quantity: 24,
    unit: 'Kamar/Malam',
    unit_price: 500000,
    total_price: 12000000,
  },
  {
    id: 'ii-02',
    invoice_id: 'inv-001',
    description: 'Sewa Kamar VIP Pengurus Kloter (2 Kamar x 3 Malam)',
    category: 'ROOM',
    quantity: 6,
    unit: 'Kamar/Malam',
    unit_price: 550000,
    total_price: 3300000,
  },
  {
    id: 'ii-03',
    invoice_id: 'inv-001',
    description: 'Pemakaian Aula Utama Cenderawasih (2 Hari)',
    category: 'FACILITY',
    quantity: 2,
    unit: 'Hari',
    unit_price: 5000000,
    total_price: 10000000,
  },
  {
    id: 'ii-04',
    invoice_id: 'inv-001',
    description: 'Pemakaian Lapangan Manasik Terbuka & Replika Ka’bah (1 Hari)',
    category: 'FACILITY',
    quantity: 1,
    unit: 'Hari',
    unit_price: 2000000,
    total_price: 2000000,
  },
  {
    id: 'ii-05',
    invoice_id: 'inv-001',
    description: 'Jasa Kebersihan Ekstra & Pengelolaan Sampah Kloter',
    category: 'SERVICE',
    quantity: 1,
    unit: 'Paket',
    unit_price: 1200000,
    total_price: 1200000,
  },
];

export const initialPayments: Payment[] = [
  {
    id: 'pay-001',
    payment_no: 'PAY/AHP/2026/0001',
    receipt_no: 'KWT/AHP/2026/0001',
    invoice_id: 'inv-001',
    reservation_id: 'rsv-001',
    amount: 28500000,
    payment_date: '2026-09-24T10:00:00Z',
    payment_method: 'TRANSFER_BSI',
    terbilang: 'Dua Puluh Delapan Juta Lima Ratus Ribu Rupiah',
    received_from: 'Kanwil Kementerian Agama Provinsi Papua',
    for_purpose: 'Pelunasan Biaya Penginapan dan Pemakaian Fasilitas Jamaah Haji Kloter 1 Jayapura (RSV/AHP/2026/00001)',
    officer_name: 'Bendahara Keuangan',
    notes: 'Transfer via BSI No. Rek 7123-4567-89',
    created_at: '2026-09-24T10:15:00Z',
  },
  {
    id: 'pay-002',
    payment_no: 'PAY/AHP/2026/0002',
    receipt_no: 'KWT/AHP/2026/0002',
    invoice_id: 'inv-002',
    reservation_id: 'rsv-002',
    amount: 10000000,
    payment_date: '2026-09-25T14:00:00Z',
    payment_method: 'TRANSFER_BPD_PAPUA',
    terbilang: 'Sepuluh Juta Rupiah',
    received_from: 'Bendahara IAIN Fattahul Muluk Papua',
    for_purpose: 'Uang Muka (DP 50%) Pelatihan Sertifikasi Pembimbing Manasik Haji Papua (RSV/AHP/2026/00002)',
    officer_name: 'Bendahara Keuangan',
    notes: 'Transfer Bank Papua No. Ref 882910492',
    created_at: '2026-09-25T14:15:00Z',
  },
  {
    id: 'pay-003',
    payment_no: 'PAY/AHP/2026/0003',
    receipt_no: 'KWT/AHP/2026/0003',
    invoice_id: 'inv-003',
    reservation_id: 'rsv-003',
    amount: 1100000,
    payment_date: '2026-09-25T15:10:00Z',
    payment_method: 'CASH',
    terbilang: 'Satu Juta Seratus Ribu Rupiah',
    received_from: 'Drs. H. Syamsuddin, M.Ag.',
    for_purpose: 'Pelunasan Penginapan Kamar VIP A201 (2 Malam)',
    officer_name: 'Bendahara Keuangan',
    notes: 'Pembayaran tunai di Kasir Penginapan Asrama Haji',
    created_at: '2026-09-25T15:10:00Z',
  },
];

export const initialRates: RateItem[] = [
  {
    id: 'rate-01',
    name: 'Tarif Standard Quad (Per Kamar)',
    category: 'KAMAR',
    target_id: 'rt-std',
    user_type: 'Umum / Instansi',
    unit: 'PER_ROOM',
    rate: 350000,
    description: 'Tarif 1 kamar 4 bed per malam',
    is_active: true,
    effective_date: '2026-01-01',
  },
  {
    id: 'rate-02',
    name: 'Tarif VIP Twin / Double',
    category: 'KAMAR',
    target_id: 'rt-vip',
    user_type: 'Pejabat / Tamu VIP',
    unit: 'PER_ROOM',
    rate: 550000,
    description: 'Tarif kamar VIP 2 bed per malam lengkap fasilitas',
    is_active: true,
    effective_date: '2026-01-01',
  },
  {
    id: 'rate-03',
    name: 'Tarif Kamar Rombongan Jamaah Haji',
    category: 'KAMAR',
    target_id: 'rt-rbg',
    user_type: 'Jamaah Haji & Umrah',
    unit: 'PER_ROOM',
    rate: 500000,
    description: 'Tarif khusus program pemberangkatan jamaah haji provinsi Papua',
    is_active: true,
    effective_date: '2026-01-01',
  },
  {
    id: 'rate-04',
    name: 'Tarif Sewa Aula Utama Cenderawasih',
    category: 'FASILITAS',
    target_id: 'fac-01',
    user_type: 'Instansi Pemerintah / Umum',
    unit: 'PER_EVENT',
    rate: 5000000,
    description: 'Pemakaian full day (08.00 - 17.00 WIT)',
    is_active: true,
    effective_date: '2026-01-01',
  },
  {
    id: 'rate-05',
    name: 'Tarif Ruang Pertemuan Asmat',
    category: 'FASILITAS',
    target_id: 'fac-02',
    user_type: 'Instansi Pemerintah / Pelatihan',
    unit: 'PER_EVENT',
    rate: 2500000,
    description: 'Pemakaian full day lengkap sound & proyektor',
    is_active: true,
    effective_date: '2026-01-01',
  },
];

export const initialNotifications: NotificationItem[] = [
  {
    id: 'notif-01',
    title: 'Reservasi Baru Menunggu Verifikasi',
    message: 'Reservasi RSV/AHP/2026/00005 dari Balai Penjaminan Mutu Pendidikan (BPMP) Papua memerlukan persetujuan.',
    type: 'RESERVATION',
    is_read: false,
    link_page: 'reservations',
    link_id: 'rsv-005',
    created_at: '2026-09-24T16:05:00Z',
  },
  {
    id: 'notif-02',
    title: 'Jadwal Check-in Hari Ini (26 Sept)',
    message: '1 Tamu VIP (Ustadz Ridwan Al-Bantani) dijadwalkan check-in di Kamar A203.',
    type: 'CHECKIN',
    is_read: false,
    link_page: 'checkin',
    link_id: 'rsv-006',
    created_at: '2026-09-26T07:30:00Z',
  },
  {
    id: 'notif-03',
    title: 'Tamu Telah Checkout — Kamar Kotor',
    message: 'Kamar A104 telah checkout. Tim Housekeeping perlu melakukan sanitasi dan penggantian linen.',
    type: 'HOUSEKEEPING',
    is_read: false,
    link_page: 'housekeeping',
    link_id: 'room-004',
    created_at: '2026-09-26T11:45:00Z',
  },
  {
    id: 'notif-04',
    title: 'Tiket Perbaikan Darurat AC Kamar A105',
    message: 'Perbaikan pendingin ruangan kamar A105 sedang dikerjakan teknisi Lukas Karoba.',
    type: 'MAINTENANCE',
    is_read: true,
    link_page: 'maintenance',
    link_id: 'mnt-01',
    created_at: '2026-09-26T08:35:00Z',
  },
  {
    id: 'notif-05',
    title: 'Pembayaran DP Bimtek Berhasil Dicatat',
    message: 'Pembayaran sebesar Rp 10.000.000 (IAIN Fattahul Muluk) telah diverifikasi Bagian Keuangan.',
    type: 'PAYMENT',
    is_read: true,
    link_page: 'payments',
    link_id: 'pay-002',
    created_at: '2026-09-25T14:20:00Z',
  },
];

export const initialAuditLogs: AuditLog[] = [
  {
    id: 'aud-01',
    user_name: 'Super Admin',
    user_role: 'SUPER_ADMIN',
    action: 'SYSTEM_INITIALIZATION',
    module: 'Sistem',
    details: 'Inisialisasi konfigurasi sistem SIPAH PAPUA dan import master data awal UPT Asrama Haji Papua',
    ip_address: '192.168.1.10',
    timestamp: '2026-09-20T08:00:00Z',
  },
  {
    id: 'aud-02',
    user_name: 'Pimpinan (Ka. UPT)',
    user_role: 'PIMPINAN',
    action: 'VERIFY_RESERVATION',
    module: 'Reservasi',
    target_id: 'RSV/AHP/2026/00001',
    details: 'Menyetujui dan memverifikasi reservasi Rombongan Jamaah Haji Kloter 1 Jayapura',
    ip_address: '192.168.1.15',
    timestamp: '2026-09-21T10:00:00Z',
  },
  {
    id: 'aud-03',
    user_name: 'Bendahara Keuangan',
    user_role: 'KEUANGAN',
    action: 'RECORD_PAYMENT',
    module: 'Keuangan',
    target_id: 'PAY/AHP/2026/0001',
    details: 'Menerbitkan Kwitansi KWT/AHP/2026/0001 senilai Rp 28.500.000 via BSI',
    ip_address: '192.168.1.22',
    timestamp: '2026-09-24T10:15:00Z',
  },
  {
    id: 'aud-04',
    user_name: 'Resepsionis',
    user_role: 'PETUGAS',
    action: 'CHECKIN_GUEST',
    module: 'Check-in',
    target_id: 'RSV/AHP/2026/00001',
    details: 'Melakukan proses check-in untuk rombongan Kloter 1 (45 Jamaah) dan menyerahkan kunci kamar',
    ip_address: '192.168.1.30',
    timestamp: '2026-09-25T14:30:00Z',
  },
  {
    id: 'aud-05',
    user_name: 'Resepsionis',
    user_role: 'PETUGAS',
    action: 'CHECKOUT_GUEST',
    module: 'Check-out',
    target_id: 'RSV/AHP/2026/00007',
    details: 'Proses checkout Kamar A104, pengembalian kunci kartu, status kamar dialihkan ke DIRTY / Housekeeping',
    ip_address: '192.168.1.30',
    timestamp: '2026-09-26T11:45:00Z',
  },
];
